drop function if exists public.ensure_yearly_registrations_table(integer);

create or replace function public.ensure_yearly_registrations_table(
    target_year integer,
    fields jsonb default '[]'::jsonb
)
returns text
language plpgsql
security definer
as $$
declare
    table_name text := format('Registrations_%s', target_year);
    column_def jsonb;
    column_name text;
    column_type text;
begin
    execute format(
        'create table if not exists public.%I (
            id bigint generated by default as identity primary key,
            created_at timestamptz not null default now(),
            paid boolean not null default false
        )',
        table_name
    );

    for column_def in
        select value from jsonb_array_elements(coalesce(fields, '[]'::jsonb))
    loop
        column_name := column_def->>'name';
        column_type := lower(coalesce(column_def->>'type', 'text'));

        if column_name is null or column_name !~ '^[a-zA-Z_][a-zA-Z0-9_]*$' then
            continue;
        end if;

        if column_type not in ('text', 'boolean', 'integer', 'text[]') then
            column_type := 'text';
        end if;

        execute format(
            'alter table public.%I add column if not exists %I %s',
            table_name,
            column_name,
            column_type
        );
    end loop;

    return table_name;
end;
$$;

revoke all on function public.ensure_yearly_registrations_table(integer, jsonb) from public;
grant execute on function public.ensure_yearly_registrations_table(integer, jsonb) to service_role;
